M48
; DRILL file {KiCad 8.0.8} date 2025-03-03T13:18:10-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-03T13:18:10-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.1535Y-2.6132
X4.1535Y-5.3691
X7.1063Y-2.6132
X7.1063Y-5.3691
M30
